plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - github-pages

markdown: kramdown
kramdown:
  math_engine: mathjax

url: "https://snooluna.github.io"
baseurl: "/LAMAS"


defaults:
  - scope:
      path: ""
    values:
      layout: "default"