# remote_theme: pages-themes/dinky@v0.2.0
theme: just-the-docs
plugins:
  # - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - github-pages
  
defaults:
  - scope:
      path: ""
    values:
      layout: "default"